import { StyleSheet } from '@react-pdf/renderer';

// Estilos para el PDF
export const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Roboto',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#B91E59',
    paddingBottom: 10,
  },
  headerLeft: {
    flexDirection: 'column',
  },
  headerRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  headerInfo: {
    flexDirection: 'column',
    flex: 1,
    marginLeft: 10,
  },
  logo: {
    width: 120,
    height: 50,
    objectFit: 'contain',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#B91E59',
    fontFamily: 'Roboto',
  },
  catalogTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#B91E59',
    fontFamily: 'Roboto',
  },
  companyName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#B91E59',
    fontFamily: 'Roboto',
  },
  subtitle: {
    fontSize: 12,
    color: '#3A2A2F',
    marginBottom: 10,
    fontFamily: 'Roboto',
  },
  date: {
    fontSize: 10,
    color: '#666666',
    fontFamily: 'Roboto',
  },
  content: {
    flex: 1,
    marginTop: 10,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 15,
    color: '#B91E59',
    borderBottomWidth: 1,
    borderBottomColor: '#EBC7E1',
    paddingBottom: 5,
    fontFamily: 'Roboto',
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  productItemGrid: {
    width: '31%',
    marginBottom: 20,
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#EBC7E1',
  },
  imageGalleryGrid: {
    position: 'relative',
    marginBottom: 10,
    height: 120,
  },
  mainImageGrid: {
    width: '100%',
    height: 120,
    objectFit: 'contain',
    marginBottom: 5,
  },
  secondaryImages: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    position: 'absolute',
    bottom: 5,
    right: 5,
  },
  secondaryImage: {
    width: 20,
    height: 20,
    marginLeft: 2,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
  },
  productList: {
    marginTop: 10,
  },
  productItemList: {
    flexDirection: 'row',
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#EBC7E1',
  },
  productListImageContainer: {
    position: 'relative',
    width: '25%',
    marginRight: 10,
    height: 80,
  },
  mainImageList: {
    width: '100%',
    height: 80,
    objectFit: 'contain',
  },
  secondaryImagesList: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    position: 'absolute',
    bottom: 2,
    right: 2,
  },
  secondaryImageList: {
    width: 15,
    height: 15,
    marginLeft: 2,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
  },
  productListContent: {
    flex: 1,
  },
  productName: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 3,
    color: '#B91E59',
    fontFamily: 'Roboto',
  },
  productSku: {
    fontSize: 8,
    color: '#666666',
    marginBottom: 3,
    fontFamily: 'Roboto',
  },
  productDescription: {
    fontSize: 8,
    color: '#3A2A2F',
    marginBottom: 5,
    fontFamily: 'Roboto',
  },
  priceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 5,
  },
  priceInfo: {
    flexDirection: 'column',
  },
  regularPrice: {
    fontSize: 8,
    textDecoration: 'line-through',
    color: '#666666',
    fontFamily: 'Roboto',
  },
  customPrice: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#B91E59',
    fontFamily: 'Roboto',
  },
  discountBadge: {
    backgroundColor: '#8FD8B9',
    color: '#FFFFFF',
    fontSize: 8,
    padding: 3,
    borderRadius: 3,
    fontFamily: 'Roboto',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: '#666666',
    fontSize: 8,
    borderTopWidth: 1,
    borderTopColor: '#EBC7E1',
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
  footerText: {
    fontSize: 8,
    color: '#666666',
    fontFamily: 'Roboto',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    fontSize: 8,
    color: '#666666',
    fontFamily: 'Roboto',
  },
  noImagePlaceholder: {
    backgroundColor: '#F5E6E8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  noImageText: {
    color: '#666666',
    fontSize: 8,
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  catalogDescription: {
    marginBottom: 20,
  },
  descriptionText: {
    fontSize: 10,
    color: '#666666',
    fontFamily: 'Roboto',
  },
  // Estilos para el contenedor de carga
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  loadingSubtext: {
    fontSize: 14,
    color: '#666',
    marginBottom: 15,
  },
  loadingProgress: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0066cc',
    marginTop: 10,
  },
});
